### ISSUE TITLE
Calling Draw() method without setting footer caused error

### ISSUE THREAD

**Issue by csgoh** [csgoh/roadmapper#3]
When roadmap draw() method is called without setting footer, it will throw the following error:

```
Traceback (most recent call last):
  File "c:\Lab\test-roadmap\test.py", line 16, in <module>
    my_roadmap.draw()
  File "C:\Lab\test-roadmap\lib\site-packages\generator\roadmap.py", line 217, in draw
    self.footer.draw(self.__painter)
AttributeError: 'NoneType' object has no attribute 'draw'
```

**Comment by csgoh** [comment]
Fixed in 0.1.0-beta3
